on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: npm install
      working-directory: ./lib
      run: npm install

    - name: run coverage
      working-directory: ./lib
      run: npm run test:coverage

    - name: Coveralls
      working-directory: ./lib
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        base-path: lib
        path-to-lcov: ./test/coverage/lcov.info
