on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib

    steps:
    - run: npm config ls -l

    - uses: actions/checkout@v1

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: npm install
      run: npm install --include dev

    - run: pwd
    - run: ls -la

    - name: run coverage
      run: npm run test:coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        base-path: lib
        path-to-lcov: ./test/coverage/lcov.info
