name: Generate Documentation
on:
  push:
    branches:
      - main
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install pnpm
        run: npm i -g pnpm

      - name: pnpm install
        run: pnpm install

      - name: generate docs
        run: npm run docs

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated documentation generation.
          file_pattern: docs/
          # Optional. Used by `git-add`
          # See https://git-scm.com/docs/git-add#_options
          add_options: '-u'

          # Optional. Skip internal call to `git fetch`
          skip_fetch: true

          # Optional. Prevents the shell from expanding filenames.
          # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
          disable_globbing: true
