name: Generate Documentation
on:
  push:
    branches:
      - main
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: generate docs
        run: npm run docs
