name: Generate Documentation
on:
  push:
    branches:
      - main
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: pnpm install
        run: pnpm install

      - run: ls -la
      - run: pwd

      - name: generate docs
        run: npm run docs
