name: Generate Documentation
on:
  push:
    branches:
      - main
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install pnpm
        run: npm i -g pnpm

      - name: pnpm install
        run: pnpm install

      - name: generate docs
        run: npm run docs

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated documentation generation.
          file_pattern: src/.
          # Optional. Used by `git-add`
          # See https://git-scm.com/docs/git-add#_options
          add_options: '-u'
