on:
  push:
    branches: [ main ]
    tags:
      - v*

name: CI

jobs:

  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Cache pnpm modules
        id: pnpm-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-npm-cache-3-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-3-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

  coverage:
    needs: dependencies
    name: Code Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: start rabbitmq server
        run: docker-compose up -d

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Cache pnpm modules
        id: pnpm-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-npm-cache-3-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-3-

      - name: run coverage
        run: npm run test:coverage

      - run: CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }} bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info

  analyze:
    needs: coverage
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Cache pnpm modules
        id: pnpm-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-npm-cache-3-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-3-

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  generate-docs:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: docs

      - name: Cache pnpm modules
        id: pnpm-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-npm-cache-3-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-3-

      - name: Purge previous docs
        run: rm -rf docs

      - name: generate docs
        run: npm run docs

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'docs --force'
          branch: docs
          author_name: cicd
          author_email: support@nestjs.pro
          committer_name: Matthew Davis
          committer_email: matthew@matthewdavis.io
          default_author: github_actor
          message: 'Generated updated documentation for https://amqp.nestjs.pro.'
          pathspec_error_handling: ignore
          push: true
          pull: 'NO-PULL'
          signoff: true


  release:
    needs:
      - analyze
      - coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Cache pnpm modules
        id: pnpm-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-npm-cache-3-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-3-

      - name: NPM Build
        run: npm --prefix lib run build

      - name: NPM Version
        run: npm --prefix lib version --allow-same-version

      - name: NPM Publish
        run: npm --prefix lib publish --allow-same-version
