name: Publish Typedoc to Github Pages
on:
  push:
    branches:
      - main
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TypeStrong/typedoc-action@v1
        with:
          publish-branch: main
          publish-dir: docs
          args: --out docs --plugin typedoc-plugin-extras --footerDate true --footerTime true --favicon assets/icon.png lib/src/index.ts --tsconfig lib/tsconfig.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
